cnblog/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.views.static import serve
from blog import views
from cnblog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login),
    path('index/', views.index),
    path('logout/', views.logout),
    re_path('^$', views.index),   # http://127.0.0.1:8000  直接访问首页
    path('get_validCode_img/', views.get_validCode_img),
    path('register/', views.register),

    path('digg/', views.digg),  # 点赞
    path('comment/', views.comment),  # 评论
    path("get_comment_tree/", views.get_comment_tree),   # 评论树

    # media配置
    # 匹配以media开头的任意路径
    re_path(r"media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),

    # 个人站点url
    # 正则规则：\w：匹配数字、字母、下划线   \W：匹配除数字、字母、下划线以外的任意字符
    # '(?P<name>...)' 分组匹配  {"username": alex}
    re_path('^(?P<username>\w+)$', views.home_site),

    # 有名分组
    re_path('^(?P<username>\w+)/(?P<condition>tag|category|archive)/(?P<param>.*)/$', views.home_site),

    # 文章详情页
    re_path('^(?P<username>\w+)/articles/(?P<article_id>\d+)$', views.article_detail),
]

blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息表：
    使用用户认证组件，用户表的字段不够用，需要继承AbstractUser类来定制一个自己的用户表。
    在继承后，不再生成auth_user表，直接使用user_info表
    """
    nid = models.AutoField(primary_key=True)
    telephone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to='avatars/', default="/avatars/default.png")   # 该字段存放每个用户的头像文件
    """
    FileField与ImageField用法类似，这个字段一定要接受一个文件对象。
    接受文件对象，django会做的事情：默认下载文件到项目的根目录；设置upload_to字段后，会下载到项目根目录的avatars目录下（没有该目录则创建一个）
    user_obj的avatar存的是文件的相对路径
    """
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)   # auto_now_add字段：这个创建时间不用赋值，默认用当前时间赋值

    blog = models.OneToOneField(to='Blog', to_field='nid', null=True, on_delete=models.CASCADE)  # 站点表和用户表一对一关系

    def __str__(self):
        return self.username


class Blog(models.Model):
    """
    博客信息表(站点)
    用户和站点一对一关系，
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site_name = models.CharField(verbose_name='站点名称', max_length=64)
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    def __str__(self):
        return self.title


class Category(models.Model):
    """
    博主个人文章分类表：Linux、python、面试心得、鸡汤
    分类表和用户表是多对一的关系，由于用户和站点是一对一，分类表与站点也是多对一的关系
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Tag(models.Model):
    """
    标签
    站点和标签绑定的是一对多的关系
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Article(models.Model):
    """
    文章表
    分类和文章的关系在这里设置为一对多关系（为了与文章和标签关系形成区分）
    用户和文章是一对多的关系
    标签与文章是多对多的关系（用中介模型创建第三张表）
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')   # 摘要
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)   # 发布时间
    content = models.TextField()  # 文章内容

    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    category = models.ForeignKey(to='Category', to_field='nid', null=True, on_delete=models.CASCADE)
    tags = models.ManyToManyField(    # 中介模型创建第三张关系表
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )

    def __str__(self):
        return self.title


class Article2Tag(models.Model):
    """
    文章和标签关系表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid', on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid', on_delete=models.CASCADE)

    class Meta:
        unique_together = [   # 联合唯一，两个字段不能重复
            ('article', 'tag'),
        ]

    def __str__(self):
        v = self.article.title + "---" + self.tag.title
        return v


class ArticleUpDown(models.Model):
    """
    文章点赞表
    哪个用户对哪个文章点赞或点灭
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True, on_delete=models.CASCADE)
    article = models.ForeignKey("Article", null=True, on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)   # True：赞，  False：灭

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]


class Comment(models.Model):
    """
    评论表
    根评论：对文章的评论
    子评论：对评论的评论
    哪一个用户对哪一篇文章在什么时间做了什么评论内容
    nid    user_id  article_id    content    parent_comment_id(null=True)
    1       1           1           111             null
    2       2           1           222             null
    3       3           1           333             null
    4       4           1           444               1
    5       5           1           555               4
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    # parent_comment = models.ForeignKey("Comment")   # 关联Comment表，本身就在Comment表中，因此是自关联
    parent_comment = models.ForeignKey('self', null=True, on_delete=models.CASCADE)   # 设置null=True,为null的情况不用存值了

    def __str__(self):
        return self.content

templates/article_detail.html
{% extends "base.html" %}

{% block content %}
    {% csrf_token %}
    <h3 class="text-center">{{ article_obj.title }}</h3>
    <div class="cont">
        {{ article_obj.content|safe }}
    </div>

    {# 文章点赞,清除浮动 #}
    <div class="clearfix">
        <div id="div_digg">
            {# 推荐 #}
            <div class="diggit action">
                <span class="diggnum" id="digg_count">{{ article_obj.up_count }}</span>
            </div>
            {# 点灭 #}
            <div class="buryit action">
                <span class="diggnum" id="bury_count">{{ article_obj.down_count }}</span>
            </div>
            <div class="clear"></div>
            <div class="diggword" id="digg_tips" style="color: red;"></div>
        </div>
    </div>

    {# 文章评论列表 #}
    <div class="comments list-group">
        <p class="tree_btn">评论树</p>
        <div class="comment_tree">

        </div>
        <script>
            // $(".tree_btn").click(function () {
            $.ajax({
                url: "/get_comment_tree/",
                type: "get",
                data: {
                    article_id: "{{ article_obj.pk }}",

                },
                success: function (data) {
                    console.log(data);  // data是一个列表，列表中包含一个个字典
                    $.each(data, function (index, comment_object) {
                        var pk = comment_object.pk;
                        var content = comment_object.content;
                        var parent_comment_id = comment_object.parent_comment_id;

                        var s = '<div class="comment_item" comment_id='+pk+' style="margin-left: 20px"><span>'+content+'</span></div>';

                        // 判断评论是根评论还是子评论
                        if (!parent_comment_id) {    // 感叹号取反
                            // 根评论
                            $(".comment_tree").append(s);
                        } else {
                            // 子评论
                            // 放入父评论的div标签
                            // 属性选择器，找到comment_id属性值对应的div
                            $("[comment_id="+parent_comment_id+"]").append(s);
                        }

                    })
                }
            })
            // })
        </script>

        <p>评论列表</p>
        <ul class="list-group comment_list">
            {% for comment in comment_list %}
                <li class="list-group-item">
                    <div>
                        <a href=""># {{ forloop.counter }}楼</a> &nbsp;&nbsp;
                        <span>{{ comment.create_time|date:"Y-m-d H:i" }}</span> &nbsp;&nbsp;
                        <a href=""><span><{{ comment.user.username }}/span></a> &nbsp;&nbsp;
                        <a class="pull-right reply_btn" username="{{ comment.user.username }}"
                           comment_pk="{{ comment.pk }}">回复</a>
                    </div>

                    {% if comment.parent_comment_id %}
                        <div class="pid_info well">
                            <p>
                                {# 拿到父评论对象评论人和评论内容 #}
                                {{ comment.parent_comment.user.username }}: {{ comment.parent_comment.content }}
                            </p>
                        </div>
                    {% endif %}

                    <div class="comment_con">
                        {# 评论内容 #}
                        <p>{{ comment.content }}</p>
                    </div>
                </li>
            {% endfor %}
        </ul>

        <p>发表评论</p>
        <p>昵称： <input type="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50"
                      value="{{ request.user.username }}"></p>
        <p>评论内容</p>
        <textarea name="" id="comment_content" cols="60" rows="10"></textarea> {# textarea是一个内联标签 #}
        <p>
            <button class="btn btn-default comment_btn">提交评论</button>
        </p>
    </div>

    <script>
        // 点赞请求
        $('#div_digg .action').click(function () {
            var is_up = $(this).hasClass("diggit");

            $obj = $(this).children("span");

            $.ajax({
                url: "/digg/",
                type: "post",
                data: {
                    'csrfmiddlewaretoken': $("[name= 'csrfmiddlewaretoken']").val(),
                    "is_up": is_up,
                    "article_id": "{{ article_obj.pk }}"
                },
                success: function (data) {
                    console.log(data);
                    if (data.state) {
                        var val = parseInt($obj.text());  // parseInt() 函数可解析一个字符串，并返回一个整数。
                        $obj.text(val + 1);
                    } else {
                        // 三元表达式
                        var val = data.handled ? "您已经推荐过！" : "您已经反对过！";
                        $("#digg_tips").html(val);

                        setTimeout(function () {
                            $("#digg_tips").html("")
                        }, 1000)
                    }
                }
            })
        });

        var pid = "";   // 父评论默认为空
        // 评论请求
        $(".comment_btn").click(function () {
            var content = $('#comment_content').val();    // 拿到评论框的内容
            if (pid) {
                // pid有值，是子评论
                // 处理拿到子评论值方法一：
                var index = content.indexOf("\n");  // 拿到换行符索引值
                content = content.slice(index + 1);  // 切片处理，从index+1一直取到最后
            }

            $.ajax({
                url: "/comment/",
                type: "post",
                data: {
                    'csrfmiddlewaretoken': $("[name= 'csrfmiddlewaretoken']").val(),
                    'article_id': "{{ article_obj.pk }}",
                    'content': content,
                    'pid': pid,
                },
                success: function (data) {
                    console.log(data);

                    // 获取视图函数返回的数据
                    var create_time = data.create_time;
                    var username = data.username;
                    var content = data.content;

                    var parent_username = data.parent_username;
                    var parent_content = data.parent_content;

                    if (pid) {
                        // ES6特性：字符串模板。
                        // ES6中允许使用反引号 ` 来创建字符串，此种方法创建的字符串里面可以包含由美元符号加花括号包裹的变量${vraible}。
                        var s = `
                    <li class="list-group-item">
                        <div>
                            <span>${create_time}</span>  &nbsp;&nbsp;
                            <a href=""><span><${username}/span></a>  &nbsp;&nbsp;
                            <a href="" class="pull-right">回复</a>
                        </div>
                        <div class="pid_info well">
                            <p>
                                {# 拿到父评论对象评论人和评论内容 #}
                                ${ parent_username }: ${ parent_content }
                            </p>
                        </div>
                        <div class="comment_con">
                            {# 评论内容 #}
                            <p>${content}</p>
                        </div>
                    </li>`;
                    } else {
                        var s = `
                    <li class="list-group-item">
                        <div>
                            <span>${create_time}</span>  &nbsp;&nbsp;
                            <a href=""><span><${username}/span></a>  &nbsp;&nbsp;
                            <a href="" class="pull-right">回复</a>
                        </div>
                        <div class="comment_con">
                            {# 评论内容 #}
                            <p>${content}</p>
                        </div>
                    </li>`;
                    }
                    // DOM操作把标签字符串整个放入ul的标签中去
                    $("ul.comment_list").append(s);

                    // 提交后清空评论框
                    $("#comment_content").val("");
                    // pid重新赋值
                    pid = "";
                }
            })
        });

        // 回复按钮事件
        $(".reply_btn").click(function () {
            $('#comment_content').focus();   // 获取焦点
            // 拿到对应的父评论的用户名
            var val = "@" + $(this).attr("username") + "\n";
            // 给输入框赋值
            $('#comment_content').val(val);
            // 拿到父评论的主键值
            pid = $(this).attr("comment_pk");

        });

    </script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- 引入 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="/static/blog/bootstrap-3.3.7/css/bootstrap.css">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="/static/js/jquery-3.3.1.js"></script>
    <!-- 引入 Bootstrap 核心 JavaScript 文件 -->
    <script src="/static/blog/bootstrap-3.3.7/js/bootstrap.js"></script> <!--依赖jquery-->
    <link rel="stylesheet" href="/static/blog/css/home_site.css">
    <link rel="stylesheet" href="/static/blog/css/article_detail.css">
</head>
<body>

<div class="header">
    <div class="content">
        <!--站点标题-->
        <p class="title">
            <span>{{ blog.title }}</span>
            <a href="" class="backend">管理</a>
        </p>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <!--添加bootstrap面板-->
            {% load my_tags %}
            {% get_classification_style username %}
        </div>
        <div class="col-md-9">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>

</body>
</html>

templates/classification.html
<div>
    <div class="panel panel-warning">
        <div class="panel-heading">我的标签</div>
        <div class="panel-body">
            {% for tag in tag_list %}
                <p><a href="/{{ username }}/tag/{{ tag.0 }}">{{ tag.0 }}({{ tag.1 }})</a></p>
            {% endfor %}
        </div>
    </div>
    <div class="panel panel-danger">
        <div class="panel-heading">随笔分类</div>
        <div class="panel-body">
            {% for cate in cate_list %}
                <p><a href="/{{ username }}/category/{{ cate.0 }}">{{ cate.0 }}({{ cate.1 }})</a></p>
            {% endfor %}
        </div>
    </div>
    <div class="panel panel-success">
        <div class="panel-heading">随笔归档</div>
        <div class="panel-body">
            {% for date in date_list %}
                <p><a href="/{{ username }}/archive/{{ date.0 }}">{{ date.0 }}({{ date.1 }})</a></p>
            {% endfor %}
        </div>
    </div>
</div>

templates/home_site.html
{% extends 'base.html' %}

{% block content %}
    <div class="article_list">
        <div class="article_list">
            {% for article in article_list %}
                <div class="article-item clearfix">
                    <h5><a href="/{{ username }}/articles/{{ article.nid }}">{{ article.title }}</a></h5>
                    <div class="article-desc">
                        {# 文章摘要 #}
                        {{ article.desc }}
                    </div>
                    <!--文章下方详细信息-->
                    <div class="small pub_info pull-right">
                        {# 文章发布时间 #}
                        <span>发布于&nbsp;&nbsp;{{ article.create_time|date:"Y-m-d H:i" }}</span> &nbsp;&nbsp;
                        {# 评论数 #}
                        <span class="glyphicon glyphicon-comment"></span> 评论({{ article.comment_count }})&nbsp;&nbsp;
                        {# 点赞数 #}
                        <span class="glyphicon glyphicon-thumbs-up"></span> 点赞({{ article.up_count }})
                    </div>
                </div>
                <hr>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客首页</title>
    <!-- 引入 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="/static/blog/bootstrap-3.3.7/css/bootstrap.css">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="/static/js/jquery-3.3.1.js"></script>
    <!-- 引入 Bootstrap 核心 JavaScript 文件 -->
    <script src="/static/blog/bootstrap-3.3.7/js/bootstrap.js"></script> <!--依赖jquery-->
    <style>
        #user_icon {
            font-size: 18px; /*调整大小*/
            margin-right: 10px; /*调整距离*/
            vertical-align: -3px; /*调整高度*/
        }
        .pub_info {
            margin-top: 10px;

        }
        .pub_info .glyphicon-comment {
            vertical-align: -1px;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">博客园</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">园子 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">新闻</a></li>
                <li><a href="#">博问</a></li>
                <li><a href="#">闪存</a></li>
                <li><a href="#">小组</a></li>
                <li><a href="#">收藏</a></li>
                <li><a href="#">招聘</a></li>
                <li><a href="#">班级</a></li>
                <li><a href="#">找找看</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    {# 已经登录 #}
                    <li><a href="#"><span id="user_icon"
                                          class="glyphicon glyphicon-user"></span>{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">修改密码</a></li>
                            <li><a href="#">修改头像</a></li>
                            <li><a href="/logout/">注销</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                {% else %}
                    {# 还未登录 #}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-warning">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

            <div class="panel panel-danger">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
<!--文章列表部分-->
<div class="col-md-6">
    <div class="article_list">
        {% for article in article_list %}
            <div class="article-item">
                <h5><a href="">{{ article.title }}</a></h5>
                <div class="article-desc">
                    <span class="media-left">
                        {# 用户头像 #}
                        <a href=""><img width="56" height="56" src="media/{{ article.user.avatar }}" alt=""></a>
                    </span>
                    <span class="media-right">
                        {# 文章摘要 #}
                        {{ article.desc }}
                    </span>
                </div>
                <!--文章下方详细信息-->
                <div class="small pub_info">
                    {# 作者 #}
                    <span><a href="">{{ article.user.username }}</a></span> &nbsp;&nbsp;&nbsp;
                    {# 文章发布时间 #}
                    <span>发布于&nbsp;&nbsp;{{ article.create_time|date:"Y-m-d H:i" }}</span> &nbsp;&nbsp;
                    {# 评论数 #}
                    <span class="glyphicon glyphicon-comment"></span> 评论({{ article.comment_count }})&nbsp;&nbsp;
                    {# 点赞数 #}
                    <span class="glyphicon glyphicon-thumbs-up"></span> 点赞({{ article.up_count }})
                </div>
            </div>
            <hr>
        {% endfor %}

    </div>
</div>
        <div class="col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

            <div class="panel panel-success">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/blog/bs/css/bootstrap.css">
</head>
<body>


<div class="container" style="margin-top: 100px">
    <div class="text-center">
        <a href="http://www.cnblogs.com/"><img src="/static/blog/img/logo_small.gif" alt="cnblogs"></a>
        <p><b>404.</b> 抱歉! 您访问的资源不存在!</p>
        <p class="d">请确认您输入的网址是否正确，如果问题持续存在，请发邮件至 404042726@qq.com 与 <strong style="font-size: 28px">老村长</strong> 联系。</p>
        <p><a href="/">返回网站首页</a></p>

    </div>
</div>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
    <link rel="stylesheet" href="/static/blog/bootstrap-3.3.7/css/bootstrap.css">
    <style>
        #avatar_img {
            margin-left: 20px;
        }

        #avatar {
            display: none;
        }

        .error {
            color: red;
        }
    </style>
</head>
<body>
<h3>注册页面</h3>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-offset-3">
            <form id="form">
                {% csrf_token %}
                {% for field in form %}
                    {# 一个个获取字段对象 #}
                    <div class="form-group">
                        <label for="{{ field.auto_id }}">{{ field.label }}</label>
                        {{ field }} <span class="error pull-right"></span>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <label for="avatar">
                        头像
                        <img id="avatar_img" width="60" height="60" src="/static/blog/img/default.png" alt="">
                    </label>
                    <input type="file" id="avatar">
                </div>
                <input type="button" class="btn btn-default reg-btn" value="提交"><span class="error"></span>
            </form>
        </div>
    </div>
</div>
<script src="/static/js/jquery-3.3.1.js"></script>
<script>
    // 头像预览
    $("#avatar").change(function () {   // change方法，当输入域发生变化时改变其颜色(在这里是上传图片时触发)
        // 获取用户选中的文件对象
        var file_obj = $(this)[0].files[0];
        // 获取文件对象路径
        var reader = new FileReader();

        reader.readAsDataURL(file_obj);

        // 修改img的src属性，src=文件对象的路径
        reader.onload = function () {  //
            // reader.result;   // 读url的结果保存在result中
            $("#avatar_img").attr("src", reader.result)   // 等事件完成之后再
        };
    });

    // 基于Ajax提交数据
    $(".reg-btn").click(function () {
        var formdata = new FormData();
        var request_data = $("#form").serializeArray();
        $.each(request_data, function (index, data) {
            // 依次循环，每次的操作
            formdata.append(data.name, data.value)
        });
        // formdata.append("user", $("#id_user").val());
        // formdata.append("pwd", $("#id_pwd").val());
        // formdata.append("re_pwd", $("#id_re_pwd").val());
        // formdata.append("email", $("#id_email").val());
        // formdata.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

        formdata.append("avatar", $("#avatar")[0].files[0]);  // 拿到用户传递的文件对象

        $.ajax({
            url: "",
            type: "post",
            contentType: false,
            processData: false,
            data: formdata,
            success: function (data) {
                // console.log(data)
                if (data.user) {
                    // 注册成功，跳转登录页面
                    location.href = "/login/"
                } else {
                    // 注册失败
                    console.log(data.msg);
                    // 清空错误信息
                    $("span.error").html("");
                    $(".form-group").removeClass("has-error");
                    // 展示此次提交的错误信息
                    $.each(data.msg, function (field, error_list) { // 键：每个字段字符串； 值：错误信息列表
                        console.log(field, error_list);
                        if (field == "__all__") {
                            // 全局错误信息
                            $("#id_re_pwd").next().html(error_list[0]).parent().addClass("has-error");
                        }
                        $("#id_" + field).next().html(error_list[0]);
                        $("#id_" + field).parent().addClass("has-error");
                    })
                }
            }
        })
    })
</script>
</body>
</html>